/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDynamicInvoiceTokenFactory,
  IDynamicInvoiceTokenFactoryInterface,
} from "../../../contracts/interfaces/IDynamicInvoiceTokenFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "dynamicInvoiceToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "paymentReference",
        type: "bytes",
      },
    ],
    name: "DynamicInvoiceTokenCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnerChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "string",
        name: "_symbol",
        type: "string",
      },
      {
        internalType: "string",
        name: "_requestId",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "_paymentReference",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "_payer",
        type: "address",
      },
      {
        internalType: "address",
        name: "_payee",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "createDynamicInvoiceToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_paymentReference",
        type: "bytes",
      },
    ],
    name: "getDynamicInvoiceToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "setOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDynamicInvoiceTokenFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IDynamicInvoiceTokenFactoryInterface {
    return new Interface(_abi) as IDynamicInvoiceTokenFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDynamicInvoiceTokenFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IDynamicInvoiceTokenFactory;
  }
}
