/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPayChunkRegistry,
  IPayChunkRegistryInterface,
} from "../../../contracts/interfaces/IPayChunkRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "contractName",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
    ],
    name: "ContractRegistered",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_contractName",
        type: "string",
      },
    ],
    name: "contracts",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_contractName",
        type: "string",
      },
      {
        internalType: "address",
        name: "_contractAddress",
        type: "address",
      },
    ],
    name: "registerContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPayChunkRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IPayChunkRegistryInterface {
    return new Interface(_abi) as IPayChunkRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPayChunkRegistry {
    return new Contract(address, _abi, runner) as unknown as IPayChunkRegistry;
  }
}
