/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IDynamicInvoiceTokenActionsInterface extends Interface {
  getFunction(nameOrSignature: "pay" | "spawnChild"): FunctionFragment;

  encodeFunctionData(functionFragment: "pay", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "spawnChild",
    values: [string, BytesLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "spawnChild", data: BytesLike): Result;
}

export interface IDynamicInvoiceTokenActions extends BaseContract {
  connect(runner?: ContractRunner | null): IDynamicInvoiceTokenActions;
  waitForDeployment(): Promise<this>;

  interface: IDynamicInvoiceTokenActionsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  pay: TypedContractMethod<[], [void], "payable">;

  spawnChild: TypedContractMethod<
    [
      _requestId: string,
      _paymentReference: BytesLike,
      _payer: AddressLike,
      _amount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "pay"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "spawnChild"
  ): TypedContractMethod<
    [
      _requestId: string,
      _paymentReference: BytesLike,
      _payer: AddressLike,
      _amount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  filters: {};
}
