/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { EthereumProxy__factory } from "./EthereumProxy__factory";
