/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDynamicInvoiceTokenImmutables,
  IDynamicInvoiceTokenImmutablesInterface,
} from "../../../../contracts/interfaces/dynamic-invoice-token/IDynamicInvoiceTokenImmutables";

const _abi = [
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "registry",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDynamicInvoiceTokenImmutables__factory {
  static readonly abi = _abi;
  static createInterface(): IDynamicInvoiceTokenImmutablesInterface {
    return new Interface(_abi) as IDynamicInvoiceTokenImmutablesInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDynamicInvoiceTokenImmutables {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IDynamicInvoiceTokenImmutables;
  }
}
