/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEthereumProxy,
  IEthereumProxyInterface,
} from "../../../../contracts/request-network/interfaces/IEthereumProxy";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes",
        name: "paymentReference",
        type: "bytes",
      },
    ],
    name: "TransferWithReference",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "_to",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_paymentReference",
        type: "bytes",
      },
    ],
    name: "transferWithReference",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IEthereumProxy__factory {
  static readonly abi = _abi;
  static createInterface(): IEthereumProxyInterface {
    return new Interface(_abi) as IEthereumProxyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEthereumProxy {
    return new Contract(address, _abi, runner) as unknown as IEthereumProxy;
  }
}
