const core = {
    PAY_CHUNK_REGISTRY_ADDRESS: process.env.NEXT_PUBLIC_PAY_CHUNK_REGISTRY_ADDRESS as any,
    DYNAMIC_INVOICE_TOKEN_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_DYNAMIC_INVOICE_TOKEN_FACTORY_ADDRESS as any,
}

export default core;