/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC20FeeProxy,
  IERC20FeeProxyInterface,
} from "../../../../../contracts/request-network/interfaces/ERC20FeeProxy.sol/IERC20FeeProxy";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes",
        name: "paymentReference",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "feeAddress",
        type: "address",
      },
    ],
    name: "TransferWithReferenceAndFee",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_paymentReference",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "_feeAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_feeAddress",
        type: "address",
      },
    ],
    name: "transferFromWithReferenceAndFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC20FeeProxy__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20FeeProxyInterface {
    return new Interface(_abi) as IERC20FeeProxyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC20FeeProxy {
    return new Contract(address, _abi, runner) as unknown as IERC20FeeProxy;
  }
}
