/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IEthereumProxyInterface extends Interface {
  getFunction(nameOrSignature: "transferWithReference"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TransferWithReference"): EventFragment;

  encodeFunctionData(
    functionFragment: "transferWithReference",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "transferWithReference",
    data: BytesLike
  ): Result;
}

export namespace TransferWithReferenceEvent {
  export type InputTuple = [
    to: AddressLike,
    amount: BigNumberish,
    paymentReference: BytesLike
  ];
  export type OutputTuple = [
    to: string,
    amount: bigint,
    paymentReference: string
  ];
  export interface OutputObject {
    to: string;
    amount: bigint;
    paymentReference: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IEthereumProxy extends BaseContract {
  connect(runner?: ContractRunner | null): IEthereumProxy;
  waitForDeployment(): Promise<this>;

  interface: IEthereumProxyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  transferWithReference: TypedContractMethod<
    [_to: AddressLike, _paymentReference: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "transferWithReference"
  ): TypedContractMethod<
    [_to: AddressLike, _paymentReference: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "TransferWithReference"
  ): TypedContractEvent<
    TransferWithReferenceEvent.InputTuple,
    TransferWithReferenceEvent.OutputTuple,
    TransferWithReferenceEvent.OutputObject
  >;

  filters: {
    "TransferWithReference(address,uint256,bytes)": TypedContractEvent<
      TransferWithReferenceEvent.InputTuple,
      TransferWithReferenceEvent.OutputTuple,
      TransferWithReferenceEvent.OutputObject
    >;
    TransferWithReference: TypedContractEvent<
      TransferWithReferenceEvent.InputTuple,
      TransferWithReferenceEvent.OutputTuple,
      TransferWithReferenceEvent.OutputObject
    >;
  };
}
