/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20FeeProxySol from "./ERC20FeeProxy.sol";
export type { erc20FeeProxySol };
import type * as ethereumFeeProxySol from "./EthereumFeeProxy.sol";
export type { ethereumFeeProxySol };
export type { IERC20ConversionProxy } from "./IERC20ConversionProxy";
export type { IEthConversionProxy } from "./IEthConversionProxy";
export type { IEthereumProxy } from "./IEthereumProxy";
